## Project Name: SICSS Git Test

Basis Data Sciene tests below

In [3]:
import numpy as np

print(np.random.rand(3, 3))

[[0.28579092 0.48188891 0.60111473]
 [0.58675412 0.57222316 0.81988667]
 [0.38436668 0.20299269 0.92809278]]
